[package]
name = "lux_rust"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "lux_rust"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.35.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
